import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHandler,finalContext} from '../supabase/functions/lab-claimed-context/handler.mjs';
const NOW=Date.parse('2026-10-02T09:00:00Z');
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];
function fixture(){
 const race={race_date:'2026-10-02',track:'船橋',race_no:12,circuit:'LOCAL',post_time:'2026-10-02T10:00:00Z',prediction_status:'PENDING',field_payload:{runners:[]}};
 const run={id:ids[0],worker_id:'RESCUE',status:'RUNNING'};
 const job={...race,id:ids[1],worker_run_id:run.id,claim_token:ids[2],claimed_by:run.worker_id,job_status:'CLAIMED',lease_until:'2026-10-02T09:15:00Z',attempts:1,max_attempts:5};
 const protocol={protocol_key:'LOCAL_MAIN',version:'CURRENT_TEST',is_active:true,content:{rules:['全頭比較契約']}};
 const state={race,run,job,protocol};
 const h={race_date:'2026-09-20',track:'東京',race_no:7,horse_no:4,source:'jra_public_reference',source_ref:'official-run',identity_source_ref:'official-horse',identity_verified_by:'OFFICIAL_RACE_HORSE_NO',finish:2,weight_carried:58,body_weight:500,data_origin:'DB_OFFICIAL_HISTORY'};
 const context={claim:{job_id:job.id,run_id:run.id,claim_token:job.claim_token},race:{...race,conditions:{distance:1800}},protocol_version:protocol.version,field_integrity_checked:true,runners:[{horse_no:4,horse_name:'シドニーホバート',weight_carried:null,body_weight:null,current_source_ref:'official-card',identity_refs:[],recent_runs:[h],missing_items:['weight_carried']}],missing_conditions:['going'],supplementation_audit:[{stage:'OFFICIAL_HISTORY',horse_no:4,outcome:'READ_OK'}]};
 const reads=[];let n=0;
 const data={lab_worker_runs:[run],lab_prediction_jobs:[job],official_races:[race],lab_prediction_protocols:[protocol]};
 const client={from(table){reads.push(table);const filters=[];return {select(){return this;},eq(k,v){filters.push([k,v]);return this;},limit(){return this;},async abortSignal(){n++;return {data:data[table].filter(r=>filters.every(([k,v])=>r[k]===v)),error:null};}};}};
 const handler=createHandler({client,serviceKey:'server-secret',now:()=>NOW,collector:async()=>context,officialFactory:()=>({})});
 const req=(body={run_id:ids[0],job_id:ids[1],claim_token:ids[2]},auth='Bearer server-secret')=>new Request('https://test',{method:'POST',headers:{authorization:auth,'content-type':'application/json'},body:JSON.stringify(body)});
 return {state,context,h,reads,handler,req,data};
}
test('success SELECT-only, rereads ownership, preserves evidence, omits token',async()=>{const f=fixture();const r=await f.handler(f.req());assert.equal(r.status,200);const o=await r.json();assert.equal(f.reads.length,8);assert.equal(o.context.runners[0].recent_runs[0].data_origin,'DB_OFFICIAL_HISTORY');assert.equal(o.context.claim,undefined);assert.deepEqual(o.context.protocol.content,{rules:['全頭比較契約']});});
for(const auth of ['', 'Bearer anon', 'Bearer authenticated', 'Bearer forged-service-role'])test('reject credential '+auth,async()=>{const f=fixture();assert.equal((await f.handler(f.req(undefined,auth))).status,401);assert.equal(f.reads.length,0);});
test('reject GET',async()=>assert.equal((await fixture().handler(new Request('https://test'))).status,405));
for(const body of [{},{run_id:ids[0],job_id:ids[1],claim_token:'bad'},{run_id:ids[0],job_id:ids[1],claim_token:ids[2],race_date:'2020-01-01'}])test('reject malformed/identity override '+JSON.stringify(body),async()=>{const f=fixture();assert.equal((await f.handler(f.req(body))).status,400);assert.equal(f.reads.length,0);});
for(const [name,change] of [
 ['stale token',f=>f.state.job.claim_token=ids[0]],['different run',f=>f.state.job.worker_run_id=ids[1]],['lease expired',f=>f.state.job.lease_until='2026-10-02T08:00:00Z'],['run finished',f=>f.state.run.status='SUCCEEDED'],['attempts exhausted',f=>f.state.job.attempts=6],['race deadline',f=>f.state.race.post_time='2026-10-02T09:03:00Z'],['race started',f=>f.state.race.post_time='2026-10-02T08:00:00Z'],['race status',f=>f.state.race.prediction_status='FROZEN'],['protocol missing',f=>f.state.protocol.is_active=false]
])test(name,async()=>{const f=fixture();change(f);assert.equal((await f.handler(f.req())).status,409);});
for(const [name,change] of [['target result',h=>h.race_date='2026-10-02'],['future date',h=>h.race_date='2026-10-03'],['after target start',h=>h.race_start_at='2026-10-02T11:00:00Z'],['future availability',h=>h.available_at='2026-10-02T09:01:00Z'],['invalid time',h=>h.result_confirmed_at='bad'],['archive',h=>h.prediction_archive=true],['no identity',h=>h.identity_verified_by=null]])test('last boundary '+name,()=>{const f=fixture();change(f.h);assert.throws(()=>finalContext(f.context,f.state,NOW));});
test('final boundary strips raw/market fields, keeps missing and past/current separate',()=>{const f=fixture();f.context.runners[0].odds=1.5;f.context.runners[0].recent_runs[0].popularity=1;f.context.runners[0].recent_runs[0].raw_html='<table>';f.context.raw_html='RAW';f.context.race.conditions.official_market={};const o=finalContext(f.context,f.state,NOW);assert.equal(o.runners[0].weight_carried,null);assert.equal(o.runners[0].body_weight,null);assert.equal(o.runners[0].recent_runs[0].weight_carried,58);assert.equal(o.runners[0].recent_runs[0].body_weight,500);assert.deepEqual(o.runners[0].missing_items,['weight_carried']);assert.equal(JSON.stringify(o).includes('raw_html'),false);assert.equal(JSON.stringify(o).includes('popularity'),false);assert.equal(JSON.stringify(o).includes('odds'),false);assert.equal(JSON.stringify(o).includes('official_market'),false);});
test('more than five rejected at final boundary',()=>{const f=fixture();f.context.runners[0].recent_runs=Array(6).fill(f.h);assert.throws(()=>finalContext(f.context,f.state,NOW));});
test('ownership changed during collection is rejected',async()=>{const f=fixture();const handler=createHandler({client:{from(table){const rows=f.data[table];return {select(){return this;},eq(){return this;},limit(){return this;},async abortSignal(){return {data:rows,error:null};}};}},serviceKey:'server-secret',now:()=>NOW,officialFactory:()=>({}),collector:async()=>{f.state.job.claim_token=ids[0];return f.context;}});assert.equal((await handler(f.req())).status,409);});

test('active JSONB content, assessment condition location retained',()=>{const f=fixture();const o=finalContext(f.context,f.state,NOW);assert.equal(o.race.conditions.distance,1800);});
test('real collector: absent history stays missing, no write, no instant retry',async()=>{const f=fixture();const runner={horse_no:4,horse_name:'シドニーホバート',status:'ACTIVE',sex_age:'牡4',weight_carried:56,jockey:'公式騎手',identity_refs:[]};f.state.race.field_payload.runners=[runner];let calls=0;
 const client={from(table){if(table==='horse_runs'||table==='jra_lab_runs')return {select(){return this;},eq(){return this;},lt(){return this;},order(){return this;},limit(){return this;},async abortSignal(){return {data:[],error:null};}};return fclient(table);}};
 function fclient(table){return {select(){return this;},eq(){return this;},limit(){return this;},async abortSignal(){return {data:f.data[table],error:null};}};}
 const h=createHandler({client,serviceKey:'server-secret',now:()=>NOW,officialFactory:()=>({readRace:async()=>({...f.state.race,runners:[runner],history:[],conditions:{distance:1800},source:'NAR_OFFICIAL_DEBA',source_ref:'https://www.keiba.go.jp/KeibaWeb/TodayRaceInfo/DebaTable?k_babaCode=19&k_raceDate=2026%2F10%2F02&k_raceNo=12',fetched_at:'2026-10-02T09:00:00Z'}),readHistory:async()=>{calls++;throw Error('unavailable');}})});
 const response=await h(f.req());assert.equal(response.status,200);const out=await response.json();assert.equal(calls,1);assert.equal(out.context.runners[0].recent_runs.length,0);assert.ok(out.context.runners[0].missing_items.includes('verified_history'));assert.equal(f.state.job.job_status,'CLAIMED');});
test('protocol switched during collection rejected',async()=>{const f=fixture();const client={from(table){return {select(){return this;},eq(){return this;},limit(){return this;},async abortSignal(){return {data:structuredClone(f.data[table]),error:null};}};}};const h=createHandler({client,serviceKey:'server-secret',now:()=>NOW,officialFactory:()=>({}),collector:async()=>{f.state.protocol.version='CHANGED';return f.context;}});assert.equal((await h(f.req())).status,409);});
test('oversize request rejected without DB access',async()=>{const f=fixture();assert.equal((await f.handler(f.req({padding:'x'.repeat(3000)}))).status,413);assert.equal(f.reads.length,0);});
test('implementation has no write/RPC execution methods',async()=>{const {readFile}=await import('node:fs/promises');for(const path of ['../supabase/functions/lab-claimed-context/handler.mjs','../supabase/functions/lab-claimed-context/index.ts']){const source=await readFile(new URL(path,import.meta.url),'utf8');assert.equal(/\.(?:rpc|insert|update|upsert|delete)\s*\(/.test(source),false);}});
