import test from 'node:test';
import assert from 'node:assert/strict';
import {queueNext,queueSave,publicError,WORKER_REGIONS} from '../supabase/functions/local-claimed-mcp/queue-operation.mjs';
const id='11111111-1111-4111-8111-111111111111',user={id:'22222222-2222-4222-8222-222222222222'};
const record={claimed:true,resumed:false,job_id:id,run_id:id,region:'RESCUE',lease_until:'2099-01-01T00:00:00Z'};
function deps(data=record,error=null){const calls=[];return {userId:user.id,calls,client:{rpc(name,args){calls.push({name,args});return {abortSignal(){return Promise.resolve({data,error});}};}}};}
test('queue tool calls only one DB wrapper and strips extra internal fields',async()=>{const d=deps({...record,claim_token:'private-test-marker',service_role:'private-test-marker'});const r=await queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},d);assert.equal(d.calls.length,1);assert.equal(d.calls[0].name,'lab_queue_claim_next_v1');assert.deepEqual(d.calls[0].args,{p_worker_id:'LOCAL_QUEUE_RESCUE'});assert.ok(!JSON.stringify(r).includes('private-test-marker'));});
for(const worker_id of Object.keys(WORKER_REGIONS))test('fixed mapping '+worker_id,async()=>{const d=deps({...record,region:WORKER_REGIONS[worker_id]});assert.equal((await queueNext({worker_id},d)).region,WORKER_REGIONS[worker_id]);});
test('no job is normal and excludes run/token',async()=>assert.deepEqual(await queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},deps({claimed:false,resumed:false,run_id:id,claim_token:'private-test-marker'})),{ok:true,claimed:false,resumed:false}));
test('resume kept',async()=>assert.equal((await queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},deps({...record,resumed:true}))).resumed,true));
for(const input of [{worker_id:'JRA_QUEUE_RESCUE'},{worker_id:'LOCAL_QUEUE_RESCUE',region:'中部'},{worker_id:'LOCAL_QUEUE_RESCUE',claim_token:id},{worker_id:'LOCAL_QUEUE_RESCUE',run_id:id},{}])test('client cannot override authorization '+JSON.stringify(Object.keys(input)),async()=>{const d=deps();await assert.rejects(queueNext(input,d));assert.equal(d.calls.length,0);});
test('helpers never invoke an auth callback',async()=>{const d=deps({ok:true,prediction_id:id,already_saved:true});d.authorize=()=>{throw Error('Must authenticate in handler only');};await queueSave({job_id:id,protocol_version:'fixture',payload:{},original_payload:{}},d);await queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},deps());});
for(const change of [{region:'wrong'},{lease_until:'broken'},{lease_until:'2000-01-01T00:00:00Z'},{job_id:null},{run_id:null},{claimed:'yes'}])test('malformed upstream fails closed '+Object.keys(change)[0],async()=>await assert.rejects(queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},deps({...record,...change})),/QUEUE_STATE_UNAVAILABLE/));
test('DB errors never echo details',async()=>{const d=deps(null,{message:'private-test-marker'});await assert.rejects(queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},d),/QUEUE_START_FAILED/);assert.equal(publicError(Error('Authorization: Bearer private-test-marker')),'OPERATION_FAILED');});
test('hung upstream is bounded',async()=>{const d=deps();d.timeoutMs=5;d.client.rpc=()=>({abortSignal:()=>new Promise(()=>{})});await assert.rejects(queueNext({worker_id:'LOCAL_QUEUE_RESCUE'},d));});
test('save passes user internally, no claim token in input/response',async()=>{const d=deps({ok:true,prediction_id:id,already_saved:false}),payload={fixture:'only'};const r=await queueSave({job_id:id,protocol_version:'fixture',original_payload:{raw:'fixture'},payload},d);assert.equal(d.calls[0].name,'lab_queue_save_prediction_v1');assert.equal(d.calls[0].args.p_user_id,user.id);assert.equal(r.prediction_id,id);assert.ok(!Object.hasOwn(r,'user_id'));assert.ok(!Object.hasOwn(d.calls[0].args,'p_claim_token'));});
test('already successful response retained without returning payload',async()=>assert.deepEqual(await queueSave({job_id:id,protocol_version:'fixture',original_payload:{raw:'fixture'},payload:{}},deps({ok:true,prediction_id:id,already_saved:true})),{ok:true,prediction_id:id,already_saved:true}));
test('save RPC errors are sanitized',async()=>await assert.rejects(queueSave({job_id:id,protocol_version:'fixture',original_payload:{raw:'fixture'},payload:{}},deps(null,{message:'password-private-test-marker'})),/SAVE_REJECTED/));
test('save user missing fails closed',async()=>{const d=deps();d.userId=undefined;await assert.rejects(queueSave({job_id:id,protocol_version:'fixture',original_payload:{raw:'fixture'},payload:{}},d));assert.equal(d.calls.length,0);});

test('original payload is forwarded independently from normalized payload',async()=>{const d=deps({ok:true,prediction_id:id,already_saved:true});const original={audit:{eye_pairwise_comparison:[{evidence_refs:['raw']}]}};const normalized={audit:{eye_pairwise_comparison:[{evidence_refs:['normalized']}]}};await queueSave({job_id:id,protocol_version:'fixture',payload:normalized,original_payload:original},d);assert.deepEqual(d.calls[0].args.p_original_payload,original);assert.deepEqual(d.calls[0].args.p_payload,normalized);});

test('safe retry mismatch code is preserved',async()=>await assert.rejects(queueSave({job_id:id,protocol_version:'fixture',payload:{},original_payload:{}},deps(null,{message:'SAVE_RETRY_MISMATCH'})),/^Error: SAVE_RETRY_MISMATCH$/));
