import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const sql=read('review/local-queue-execution-migration.sql');
test('SQL uses transaction-scoped worker lock and existing enqueue/start/claim/finish only',()=>{assert.match(sql,/pg_advisory_xact_lock\(72816, hashtext\(p_worker_id\)\)/);assert.match(sql,/AT TIME ZONE 'Asia\/Tokyo'/);for(const n of ['lab_enqueue_prediction_jobs','lab_start_worker_run','lab_claim_prediction_jobs','lab_finish_worker_run'])assert.ok(sql.includes('public.'+n));assert.match(sql,/lab_claim_prediction_jobs\(v_run_id,1,900\)/);});
test('SQL returns live claim rather than steals and empty run closes',()=>{assert.match(sql,/IF v_live=1 THEN/);assert.match(sql,/'resumed',true/);assert.match(sql,/lab_finish_worker_run\(v_run_id,'SUCCEEDED',NULL\)/);assert.match(sql,/v_live>1/);assert.match(sql,/QUEUE_STATE_UNAVAILABLE/);});
test('receipt and nested original guarded save share transaction; no direct prediction DML',()=>{assert.match(sql,/public\.lab_save_claimed_prediction\(v_run.id,p_job_id/);assert.match(sql,/INSERT INTO public\.lab_local_queue_save_receipts/);assert.match(sql,/p\.payload=p_payload/);assert.match(sql,/r\.user_id=p_user_id/);assert.doesNotMatch(sql,/(INSERT\s+INTO|UPDATE|DELETE\s+FROM|TRUNCATE)\s+public\.official_predictions/i);});
test('additive SQL never alters original functions or JRA objects',()=>{assert.doesNotMatch(sql,/CREATE(?: OR REPLACE)? FUNCTION public\.lab_(?:save_claimed_prediction|claim_prediction_jobs|start_worker_run)\(/);assert.doesNotMatch(sql,/public\.jra_/i);assert.doesNotMatch(sql,/DELETE\s+FROM/i);});
test('security invoker, fixed path and client revoked',()=>{assert.equal((sql.match(/SECURITY INVOKER/g)||[]).length,2);assert.doesNotMatch(sql,/SECURITY DEFINER/);assert.equal((sql.match(/FROM PUBLIC,anon,authenticated/g)||[]).length,2);assert.match(sql,/REVOKE ALL ON public\.lab_local_queue_save_receipts FROM service_role/);assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/GRANT SELECT,INSERT ON public\.lab_local_queue_save_receipts TO service_role/);});
test('full LOCAL eye validator/context modules unchanged from source-import commit',()=>{for(const [p,hash] of Object.entries(JSON.parse(read('review/source-import-hashes.json'))))assert.equal(createHash('sha256').update(read(p)).digest('hex'),hash,p);});
test('source archive contains no embedded refresh credential or JWT',()=>{const s=read('supabase/functions/local-data-refresh/index.ts');assert.match(s,/Deno\.env\.get\('LOCAL_DATA_REFRESH_KEY'\)/);assert.doesNotMatch(s,/const REFRESH_KEY\s*=\s*["'][^"']+["']/);assert.doesNotMatch(read('supabase/functions/local-claimed-mcp/index.ts'),/eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\./);});

test('receipt grants explicitly clear all four principals before minimal grant',()=>{for(const role of ['PUBLIC','anon','authenticated','service_role'])assert.ok(sql.includes('REVOKE ALL ON public.lab_local_queue_save_receipts FROM '+role+';'));assert.match(sql,/GRANT SELECT,INSERT ON public\.lab_local_queue_save_receipts TO service_role/);});
test('original payload JSONB and normalized prediction JSONB are both checked',()=>{assert.match(sql,/original_payload jsonb NOT NULL/);assert.match(sql,/v_receipt\.original_payload IS DISTINCT FROM p_original_payload/);assert.match(sql,/p\.payload=p_payload/);assert.doesNotMatch(sql,/CREATE EXTENSION|SECURITY DEFINER/);});
test('expired ownership validates worker/run/region before any cleanup',()=>{const start=sql.indexOf('-- Check expired ownership');const end=sql.indexOf('-- Only this worker',start);const s=sql.slice(start,end);assert.ok(start>0&&end>start);for(const text of ['j.worker_run_id','r.worker_id','r.region','j.claimed_by','s.region=j.region','QUEUE_STATE_UNAVAILABLE'])assert.ok(s.includes(text));assert.ok(!s.includes('j.lease_until >'));});
