import test from 'node:test';import assert from 'node:assert/strict';import {dbTimeFetch,jwtTimes} from './candidate/db-time.mjs';
const err=(message='JWT issued at future')=>new Response(JSON.stringify({message}),{status:401});
const request=method=>new Request('https://offline.invalid',{method,headers:{authorization:'Bearer fixture',apikey:'fixture'}});
test('future JWT read retries once, preserving headers and server validation',async()=>{let n=0;const waits=[];const f=dbTimeFetch('fixture',async r=>{assert.equal(r.headers.get('authorization'),'Bearer fixture');return ++n===1?err():new Response('{}')},async ms=>waits.push(ms),()=>{});assert.equal((await f(request('GET'))).status,200);assert.equal(n,2);assert.deepEqual(waits,[1100])});
test('persistent future JWT fails closed after one retry',async()=>{let n=0;assert.equal((await dbTimeFetch('fixture',async()=>{n++;return err()},async()=>{},()=>{})(request('GET'))).status,401);assert.equal(n,2)});
test('writes never replayed',async()=>{for(const method of ['POST','PATCH','DELETE']){let n=0;await dbTimeFetch('fixture',async()=>{n++;return err()},()=>{throw Error('wait forbidden')},()=>{})(request(method));assert.equal(n,1)}});
test('other auth failures never replayed',async()=>{let n=0;await dbTimeFetch('fixture',async()=>{n++;return err('JWT expired')},()=>{throw Error('wait forbidden')},()=>{})(request('GET'));assert.equal(n,1)});
test('success never replayed',async()=>{let n=0;await dbTimeFetch('fixture',async()=>{n++;return new Response('{}')},()=>{throw Error('wait forbidden')},()=>{})(request('GET'));assert.equal(n,1)});
test('diagnostics never disclose credentials or arbitrary JWT claims',async()=>{const key='x.'+btoa(JSON.stringify({iat:1,nbf:2,exp:3,secret:'NEVER_PRINT'}))+'.signature';const logs=[];await dbTimeFetch(key,async()=>new Response('{}'),async()=>{},(...x)=>logs.push(x))(new Request('https://offline.invalid',{headers:{authorization:`Bearer ${key}`,apikey:key}}));const s=JSON.stringify(logs);assert.equal(s.includes(key),false);assert.equal(s.includes('NEVER_PRINT'),false);assert.equal(s.includes('signature'),false);assert.deepEqual(jwtTimes(key,4),{format:'jwt',utc_ms:4,iat:1,nbf:2,exp:3})});
