-- Additive fixture after automation-schema.sql; disposable local database only.
-- Protocol column/key and registry-trigger behavior read-only inspected from
-- production on 2026-10-02. No production DDL is run by this test fixture.
CREATE TABLE public.lab_prediction_protocols (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protocol_key text NOT NULL,
  version text NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  content jsonb NOT NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (protocol_key,version)
);
ALTER TABLE public.lab_prediction_protocols ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.lab_prediction_protocols FROM PUBLIC, anon, authenticated;
GRANT SELECT, UPDATE ON public.lab_prediction_protocols TO service_role;
GRANT INSERT ON public.official_predictions TO service_role;
GRANT UPDATE ON public.official_races TO service_role;

-- Reproduce the observed existing AFTER INSERT registry update. SECURITY
-- DEFINER here models that existing trigger, not the new SECURITY INVOKER RPC.
CREATE FUNCTION public.phase2a_fixture_registry() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
BEGIN
  INSERT INTO public.official_races (
    race_date,track,race_no,circuit,race_name,post_time,source,prediction_status,updated_at
  ) VALUES (
    NEW.race_date,NEW.track,NEW.race_no,NEW.circuit,NEW.race_name,NEW.post_time,
    'PREDICTION','FROZEN',now()
  )
  ON CONFLICT (race_date,track,race_no,circuit) DO UPDATE SET
    race_name = coalesce(EXCLUDED.race_name,public.official_races.race_name),
    post_time = coalesce(EXCLUDED.post_time,public.official_races.post_time),
    prediction_status = 'FROZEN', prediction_last_error = NULL, updated_at = now();
  RETURN NEW;
END
$$;
REVOKE ALL ON FUNCTION public.phase2a_fixture_registry() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER phase2a_fixture_registry AFTER INSERT ON public.official_predictions
FOR EACH ROW EXECUTE FUNCTION public.phase2a_fixture_registry();