import test from 'node:test';import assert from 'node:assert/strict';
import {inspectField,planRace,createShadowFixedRecord,planBatch} from './entry-policy.mjs';
const field=()=>({race:{circuit:'JRA',race_date:'2026-10-11',track:'fixture',race_no:1},complete:true,acquired_at:'2026-10-11T00:00:00Z',source_url:'https://www.jra.go.jp/fixture',html_sha256:'a'.repeat(64),runners:[1,2,3].map(horse_no=>({horse_no,horse_name:'fixture'+horse_no,entry_status:'ACTIVE',status_evidence:{scope:'CURRENT_RACE',verified:true,locator:'synthetic',basis:'synthetic explicit state'}}))});
function evaluation(f){return {field_signature:inspectField(f).signature,payload:{runners:f.runners.filter(r=>r.entry_status==='ACTIVE').map((r,i)=>({horse_no:r.horse_no,horse_name:r.horse_name,rank:i+1,grade:'C',reason:'fixture'})),top5:[],eye:null,bets:[],summary:'fixture',bet_strategy:'fixture',audit:{fixture:true}}};}
test('normal field is ready only after matching evaluation',()=>{const f=field();assert.equal(planRace(f).state,'REEVALUATE_ALL_ACTIVE');assert.equal(planRace(f,{evaluation:evaluation(f)}).state,'READY_TO_FREEZE')});
for(const status of ['CANCELLED','EXCLUDED'])test('pre-freeze '+status+' excludes runner and requires full remaining evaluation',()=>{const f=field(),old=evaluation(f);f.runners[1].entry_status=status;const p=planRace(f,{evaluation:old});assert.equal(p.state,'REEVALUATE_ALL_ACTIVE');assert.deepEqual(p.active.map(r=>r.horse_no),[1,3]);assert.throws(()=>createShadowFixedRecord(f,old,{recorded_at:'2026-10-11T00:01:00Z'}),/REEVALUATE/);assert.equal(planRace(f,{evaluation:evaluation(f)}).state,'READY_TO_FREEZE')});
test('unknown only holds its race',()=>{const bad=field();bad.runners[0].entry_status='UNKNOWN';assert.deepEqual(planBatch([{field:bad},{field:field()}]).map(r=>r.state),['HOLD','REEVALUATE_ALL_ACTIVE'])});
test('past cancellation evidence cannot establish current state',()=>{const f=field();f.runners[0].status_evidence.scope='HISTORY';assert.equal(inspectField(f).reason,'STATUS_UNKNOWN')});
test('missing source or unverified status holds',()=>{const f=field();delete f.html_sha256;assert.equal(inspectField(f).state,'HOLD');const g=field();g.runners[0].status_evidence.verified=false;assert.equal(inspectField(g).state,'HOLD')});
test('after freeze cancellation preserves rank grade EYE and all audit without mutating record',()=>{const f=field(),e=evaluation(f),fixed=createShadowFixedRecord(f,e,{recorded_at:'2026-10-11T00:01:00Z'}),before=structuredClone(fixed);f.runners[0].entry_status='CANCELLED';const p=planRace(f,{frozen:fixed});assert.equal(p.state,'FROZEN_UNCHANGED');assert.deepEqual(p.fixed_record,before);assert.deepEqual(fixed,before);assert.deepEqual(fixed.payload,e.payload)});
test('repeated post-freeze handling and unknown keep original fixed record',()=>{const f=field(),fixed=createShadowFixedRecord(f,evaluation(f),{recorded_at:'2026-10-11T00:01:00Z'});const a=planRace(null,{frozen:fixed}),b=planRace(null,{frozen:a.fixed_record});assert.deepEqual(a.fixed_record,b.fixed_record)});
test('snapshot retains acquisition time and each status; returned copies isolated',()=>{const f=field();f.runners[2].entry_status='EXCLUDED';const x=createShadowFixedRecord(f,evaluation(f),{recorded_at:'2026-10-11T00:01:00Z'});assert.equal(x.input_state_snapshot.acquired_at,f.acquired_at);assert.equal(x.input_state_snapshot.runners[2].entry_status,'EXCLUDED');f.runners[2].entry_status='ACTIVE';assert.equal(x.input_state_snapshot.runners[2].entry_status,'EXCLUDED')});
test('no artificial wait until post time required',()=>assert.equal(planRace(field(),{evaluation:evaluation(field())}).state,'READY_TO_FREEZE'));
test('excluded runner cannot remain in completed payload',()=>{const f=field(),e=evaluation(f);f.runners[2].entry_status='EXCLUDED';e.field_signature=inspectField(f).signature;assert.throws(()=>createShadowFixedRecord(f,e,{recorded_at:'2026-10-11T00:01:00Z'}),/COVERAGE/)});
